#!/data/data/com.termux/files/usr/bin/bash

# Config

MUSIC="$HOME/storage/music"
ASMR="/sdcard/.nsfw"
VIDEOS="$HOME/storage/movies"
CLIPS="$HOME/storage/movies/Clips"
DOWNLOADS="$HOME/storage/downloads"

# End

bashrc="$HOME/.bashrc"
if [ -f "$bashrc" ]; then
    source "$bashrc"
fi

url=$1

echo $url

# Site regexs
yt="^(https?\:\/\/)?(((www|m)\.)?youtube\.com|youtu\.be)\/.+$"

# Functions for downloading 
asmr() {
  echo ASMR
  yt-dlp -f bestaudio --extract-audio --embed-thumbnail --embed-metadata \
    --external-downloader aria2c --external-downloader-args "-x 16  -k 1M" \
    -o "$ASMR/yt/%(channel)s/%(upload_date)s-%(title).150B-%(id)s.%(ext)s" --no-mtime $url
}

music() {
  echo Music
  yt-dlp -f bestaudio --extract-audio --embed-thumbnail --embed-metadata \
    --external-downloader aria2c --external-downloader-args "-x 16 -k 1M" \
    --postprocessor-args "-filter:v crop=in_h" \
    -o "$MUSIC/%(title)s.%(ext)s" --no-mtime $url
}

video() {
  echo Video
  yt-dlp $url -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4' \
    -o "$VIDEOS/%(title)s-%(id)s.%(ext)s" \
    --external-downloader aria2c --external-downloader-args "-x 16 -k 1M" \
    --embed-subs --embed-thumbnail --embed-metadata \
    -S res,hdr,fps,vcodec:av01:h265:vp9.2:vp9:h264,vbr \
    --no-mtime
}

aria() {
  aria2c -x16 -d $DOWNLOADS \
    --on-download-complete "$HOME/bin/openfile" \
    $url
  exit
}

spot() {
  spotdl $url --output $MUSIC
  exit
}

play_audio() {
  mpv --no-video $url
  exit
}

yt() {
  method="$(termux-dialog sheet -v "ASMR,Music,Video,Play in mpv" | jq '.index' -r)"
  case $method in
  0)
    asmr
  ;;
  1)
    music
  ;;
  2)
    video
  ;;
  3)
    play_audio
  ;;
  *)
    exit
  ;;
  esac
}

uns() {
  method="$(termux-dialog sheet -v "Music,Video,Aria" | jq '.index' -r)"
  case $method in
  0)
    music
    ;;
  1)
    video
    ;;
  2)
    aria
    ;;
  esac
}

# Enable extglob for regex
shopt -s extglob

# Check what site is being passed
case $url in
https://music.youtube.com/watch?v=+([a-zA-Z0-9_-])*)
  music
;;
*youtube.com* | *youtu.be*)
  echo Download a yt vid
  yt
;;
*twitter*)
  echo twitter
  video
;;
*sourceforge* | *zippyshare*)
  echo download file
  aria
;;
*spotify*)
  spot
;;
*)
  echo "unsupported site"
  uns
;;
esac

termux-toast -s "Download Done"
